### PR TITLE
WIP: Rewrite the driver with only virsh commands

### PR DESCRIPTION
**Pull request by guillaumerose**
The driver can be now statically compiled and embedded as a go routine
in crc.

---

Apart from network.IsActive(), I have all features and the same behaviour. I found it to be more  readable at the end: no more conn nor vm field.

I changed the way we find the IP by looking at the DHCP info from libvirt instead of looking at DNS records in a predefined file.

### CODE REVIEW

**Review by cfergeau — COMMENTED** [review]
To be honest, this feels like a step backwards to me, switching from a proper API with error reporting, ... to exec'ing external processes and parsing their output is not very enticing.

**Comment by cfergeau** [comment]
> Apart from network.IsActive(), I have all features and the same behaviour.

Isn't this the 'active' field in `virsh net-list`/`virsh net-info`?

> I changed the way we find the IP by looking at the DHCP info from libvirt instead of looking at DNS records in a predefined file.

`virsh domifaddr` might be doing this directly?

**Comment by guillaumerose** [comment]
> virsh net-info

Yes I saw it but I would have preferred a XML output. I added a regexp for that :( - It's the only place where I have to do a grep like.

> virsh domifaddr

No XML output also :/

---

I think I've reached a state I like. I rewrote the complete XML of the domain using structs. It highlighted by itself why it's better: https://github.com/code-ready/machine-driver-libvirt/blob/master/constants.go#L22 and https://github.com/code-ready/machine-driver-libvirt/blob/master/constants.go#L31 are duplication (impossible to write when using a struct).

If you like it also, I will split this PR in 3:
* Switch to libvirt XML
* Remove the read of dns file.
* Use virsh

**Comment by cfergeau** [comment]
> > virsh net-info
> 
> Yes I saw it but I would have preferred a XML output. I added a regexp for that :( - It's the only place where I have to do a grep like.
> 
> > virsh domifaddr
> 
> No XML output also :/

Not overly surprising, as the way I see virsh is that it's a tool for interacting with libvirt *when you cannot use libvirt.so instead*. It's not meant to be a libvirt.so wrapper that you use when you don't want to link directly with the shared library ;)

**Comment by guillaumerose** [comment]
Would be better to use digitalocean library since it's supported now.

**Pull request closed without merging**
