### PR TITLE
Disk resize

### PR DESCRIPTION
**Pull request by cfergeau**
This set of commits adds disk resize support to the libvirt machine driver. It starts by adding libvirt storage pool support so that `virStorageVolResize` can be used.

### CODE REVIEW

**Comment by guillaumerose** [comment]
Would it possible to extract the storage pool code to an other file and in an other struct than the Driver? This file and struct are really too big.

Since we break previous installation, do we need to take extra precaution or just a sentence in the release notes is enough ?

**Comment by cfergeau** [comment]
> Would it possible to extract the storage pool code to an other file and in an other struct than the Driver? This file and struct are really too big.

Sure I can move the storage pool code to a separate file. Not sure which struct you refer to?

 
> Since we break previous installation, do we need to take extra precaution or just a sentence in the release notes is enough ?

We have strong ties between bundle version <-> crc version <-> machine driver version, crc releases won't start unless you use exactly the right versions. Usually we did not give much thought to backward compat with this reasoning. We should try to be more flexible than that, but I definitely did not try hard here :)

**Comment by guillaumerose** [comment]
I refer to the Driver struct. Almost all methods belong to it. `func (d *Driver) getPool()`. I didn't count but it starts to become huge. We can do that later perhaps.

**Review by guillaumerose — APPROVED** [review]

**Pull request merged**
